# Generated by Django 2.0.3 on 2018-05-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180420_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='com_title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=None, related_name='comment', to='forum.Post'),
        ),
    ]
