# Generated by Django 2.0.3 on 2018-05-07 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.OneToOneField(default=1, on_delete=None, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
