# Generated by Django 2.0.3 on 2018-05-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_auto_20180508_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
