# Generated by Django 2.0.3 on 2018-05-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_remove_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
