# Generated by Django 2.0.3 on 2018-05-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_auto_20180511_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
