# Generated by Django 2.0.3 on 2018-06-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0029_auto_20180605_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
