# Generated by Django 2.0.3 on 2018-06-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0030_auto_20180619_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='com_body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='comment',
            name='com_content',
            field=models.TextField(default=1, max_length=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=1, max_length=2500),
            preserve_default=False,
        ),
    ]
