# Generated by Django 2.0.3 on 2018-07-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0031_auto_20180619_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='com_content',
            new_name='com_innhold',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='innhold',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='tittel',
        ),
    ]
