# Generated by Django 2.0.3 on 2018-07-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0033_auto_20180714_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='tittel',
        ),
    ]
