# Generated by Django 2.0.3 on 2018-08-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0034_auto_20180714_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='correct',
            field=models.BooleanField(default=True),
        ),
    ]
