# Generated by Django 2.0.3 on 2018-08-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0035_comment_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
